version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=loandb
      - POSTGRES_USER=loanguy
      - POSTGRES_PASSWORD=l0@nguy
  web:
    build:
      context: .
      dockerfile: Dockerfile-backend
    command: python manage.py runserver 0.0.0.0:8000
    stdin_open: true
    tty: true
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=loandb
      - POSTGRES_USER=loanguy
      - POSTGRES_PASSWORD=l0@nguy
    restart: on-failure
    depends_on:
      - db
    links:
      - db
