version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=loandb
      - POSTGRES_USER=loanguy
      - POSTGRES_PASSWORD=l0@nguy
  web:
    build:
      context: .
      dockerfile: Dockerfile-backend
    command: python manage.py runserver 0.0.0.0:8000
    stdin_open: true
    tty: true
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=loandb
      - POSTGRES_USER=loanguy
      - POSTGRES_PASSWORD=l0@nguy
    restart: on-failure
    depends_on:
      - db
    links:
      - db
  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    restart: always
    volumes:
      - ./frontend:/opt/frontend
    stdin_open: true
    tty: true
    ports:
      - "8080:8080"
    environment:
      - VUE_APP_API_ENDPOINT_URL=http://139.59.225.243:8000/api/v1/
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - db
      - web
