# Generated by Django 3.2 on 2022-01-15 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=300)),
                ('contact_number', models.CharField(max_length=50)),
                ('birth_date', models.CharField(max_length=50)),
                ('pension', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sss_no', models.CharField(max_length=150)),
                ('co_maker', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.IntegerField()),
                ('interest', models.DecimalField(decimal_places=2, max_digits=5)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_granted', models.DateField()),
                ('start_payment', models.DateField()),
                ('maturity_date', models.DateField()),
                ('loan_type', models.CharField(choices=[('pension', 'Pension'), ('salary', 'Salary')], default='pension', max_length=50)),
                ('is_advance', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.client')),
            ],
        ),
    ]
