# Generated by Django 3.2 on 2022-01-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_loan_loan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='date_granted',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='maturity_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='start_payment',
            field=models.DateField(null=True),
        ),
    ]
