# Generated by Django 3.2 on 2022-01-18 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220115_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='fee_others',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
