# Generated by Django 3.2 on 2022-01-18 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_loan_fee_others'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan_detail',
            name='date_paid',
            field=models.DateField(null=True),
        ),
    ]
