# Generated by Django 3.2 on 2022-01-19 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_collection_detail_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection_detail',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.collection'),
        ),
    ]
