# Generated by Django 3.2 on 2022-01-19 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_collection_detail_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='refundable_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
