# Generated by Django 3.2 on 2022-01-20 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_collection_refundable_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('account', models.CharField(choices=[('assets', 'Assets'), ('liabilities', 'Liabilities'), ('equity', 'Equity')], max_length=50)),
                ('post_date', models.DateField(auto_now_add=True)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_side', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
