# Generated by Django 3.2 on 2022-01-20 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='llrf',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='processing_fee',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
