# Generated by Django 3.2 on 2022-01-20 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_loan_net_cash_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='net_cash_out',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
