# Generated by Django 3.2 on 2022-01-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_loan_net_cash_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='post_date',
            field=models.DateField(null=True),
        ),
    ]
