# Generated by Django 3.2 on 2022-02-25 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_transaction_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='gross_cash_out',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='net_adjustment',
            field=models.DecimalField(decimal_places=2, help_text='To deduct on net cash out when there is outstanding balance', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='udi',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
