# Generated by Django 3.2 on 2022-02-25 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20220225_0520'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='control_number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
