# Generated by Django 3.2 on 2022-02-25 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_loan_control_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='account_number',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='bank_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='birth_date',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='co_maker',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='middle_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='sss_no',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
