# Generated by Django 3.2 on 2022-03-20 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('main', '0022_auto_20220320_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection_detail',
            name='loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.loan'),
        ),
        migrations.AlterField(
            model_name='collection_detail',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='collection_detail',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
