# Generated by Django 3.2 on 2022-03-23 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_loan_is_cash_advance'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='add_fee_others',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='co_maker',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
