# Generated by Django 3.2 on 2022-03-23 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20220323_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='classification',
            field=models.CharField(choices=[('pension', 'Pension'), ('salary', 'Salary')], default='pension', max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='pension_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
