# Generated by Django 3.2 on 2022-03-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20220323_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='net_adjustment',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='To deduct on net cash out when there is outstanding balance', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='loan_detail',
            name='date_paid',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan_detail',
            name='payable',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='loan_detail',
            name='receivable',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
