# Generated by Django 3.2 on 2022-04-03 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20220403_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='co_maker_2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
