# Generated by Django 3.2 on 2022-05-31 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_loan_co_maker_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='spouse_dob',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='spouse_dod',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='spouse_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
