# Generated by Django 3.2 on 2022-06-11 01:57

from django.db import migrations, models

def populate_total_amount_to_pay(apps, _):
    Collection = apps.get_model('main', 'Collection')
    Loan = apps.get_model('main', 'Loan')
    collections = Collection.objects.all()

    for collection in collections:
        loans_id = collection.collection_details.all().values_list('loan__pk')
        loans = Loan.objects.filter(pk__in=loans_id)

        total_amount_to_pay = 0
        for loan in loans:
            total_amount_to_pay += loan.loan_detail_set.first().amount

        collection.total_amount_to_pay = total_amount_to_pay
        collection.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_auto_20220531_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='total_amount_to_pay',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.RunPython(populate_total_amount_to_pay),
    ]
